#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version

In [3]:
print(np.version.version)

1.21.5


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
np_array = np.zeros(10)
np_array.shape

(8,)

In [ ]:
#Problem 4: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 4. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [15]:
# Ghosts
array_1 = np.array([[1,2,3],[4,5,6]])
print(array_1[array_1<4])

[1 2 3]


#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)

In [36]:
# 5th - Ghosts
array_5 = np.arange(10, 50)
print(array_5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6. Reverse a vector (first element becomes last) (★☆☆)

In [46]:
# 6th - Ghosts
array_5 = np.arange(10, 50)
rev_array_5 = array_5[::-1]
print(rev_array_5)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [47]:
# 7th - Ghosts
array_7 = np.arange(0,9)
array_7_reshape = array_7.reshape(3,3)
print(array_7_reshape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [39]:
# 8th - Ghosts
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


In [53]:
import numpy as np
n= np.array([1,2,0,0,4,0])
x = np.where(n != 0)[0]
print(x)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [56]:
# 11th - Ghosts 
identity_using_fn = np.identity(3, dtype=int)
print(identity_using_fn)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [40]:
# 12th - Ghosts
random_values = random.sample(range(1, 50), 3*3*3)
random_values_array = np.array(random_values)
dim_3_array = random_values_array.reshape(3,3,3)
print(dim_3_array)

[[[ 8 39  4]
  [23 29 35]
  [31  3 24]]

 [[ 6 13 36]
  [42 27  1]
  [47  7 16]]

 [[30 37 40]
  [33 44 19]
  [32 26 41]]]


In [3]:
# 12th - Ghosts
import random
import numpy as np
dim_3_array= np.random.random((3,3,3))
print(dim_3_array)

[[[0.00701379 0.85830649 0.90732491]
  [0.97419016 0.7402898  0.11725347]
  [0.97484949 0.85709145 0.00155206]]

 [[0.07172827 0.40125679 0.22143592]
  [0.81501602 0.39350778 0.00489389]
  [0.82952162 0.40684686 0.18531105]]

 [[0.98599087 0.30440972 0.70410834]
  [0.88313514 0.57134646 0.75335194]
  [0.35765572 0.20341472 0.06244957]]]


In [74]:
# 12th - Ghosts
dim_3 = np.random.randint(1,50,(3,3,3))
print(dim_3)

[[[ 9 21 12]
  [25 12 19]
  [36 46 21]]

 [[11 18 19]
  [33 49 12]
  [17 34 21]]

 [[46 21 12]
  [28  1 43]
  [ 8 15 46]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
# 13th - Ghosts
import random
import numpy as np
dim_10_10= np.random.randint(1,50,(10,10))
print(dim_10_10)
print("\nMinimum Values\nColumnwise(Axis=0): ",np.min(dim_10_10, axis=0))
print("Row-wise(Axis=1): ",np.min(dim_10_10, axis=1))
print("Among Total-values(Axis=None): ",np.min(dim_10_10, axis=None))
print("\nMaximum Values\nColumnwise(Axis=0): ",np.max(dim_10_10, axis=0))
print("Row-wise(Axis=1): ",np.max(dim_10_10, axis=1))
print("Among Total-values(Axis=None): ",np.max(dim_10_10, axis=None))

[[ 8 15 26 46 22 25 45 25 25  9]
 [17 17  1 44 12  3 22 13 23 30]
 [19 32 12 32  5  2 12 16 48 16]
 [ 6 33 20 34 36 19 43 42 35 20]
 [34 21 25 46 33 25  1  2 12 33]
 [28 47 47 23 30  7 27 32 34 35]
 [32 48 12 43 26 31 12 26 38 17]
 [35 42 16 42  8 17  8 40 25  4]
 [ 5 23 39 38 26 35 11 48 27 16]
 [44 37 38 22 34  3 26 18 32 27]]

Minimum Values
Columnwise(Axis=0):  [ 5 15  1 22  5  2  1  2 12  4]
Row-wise(Axis=1):  [ 8  1  2  6  1  7 12  4  5  3]
Among Total-values(Axis=None):  1

Maximum Values
Columnwise(Axis=0):  [44 48 47 46 36 35 45 48 48 35]
Row-wise(Axis=1):  [46 44 48 43 46 47 48 42 48 44]
Among Total-values(Axis=None):  48


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
# 14th - Ghosts
dim_30= np.random.randint(1,50,(1,30))
print(dim_30)
print(len(dim_30))
print("\nMean Values\nColumnwise(Axis=0): ",np.mean(dim_30, axis=0))
# print("Row-wise(Axis=1): ",np.mean(dim_30, axis=1))
print("Among Total-values(Axis=None): ",np.mean(dim_30, axis=None))

[[ 2 45 46 43 48 30 36  6 43 27 27 22 37 21 28 37 48 41 29 11 30 40 18 11
   1 42  4 43 42 20]]
1

Mean Values
Columnwise(Axis=0):  [ 2. 45. 46. 43. 48. 30. 36.  6. 43. 27. 27. 22. 37. 21. 28. 37. 48. 41.
 29. 11. 30. 40. 18. 11.  1. 42.  4. 43. 42. 20.]
Among Total-values(Axis=None):  29.266666666666666


In [23]:
# 14th - Ghosts
dim_30= np.random.randint(1,50,(30))
print(dim_30)
print(len(dim_30))
print("Among Total-values(Axis=None): ",np.mean(dim_30, axis=None))

[41  8 41 20 23 49 26 49  6 14 12 29 11 13 29 34 38  2  6 33 48 25 30 20
 20 14 43 49  4 17]
30
Among Total-values(Axis=None):  25.133333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
# 15th - Ghosts

n = 5
m = 4
print("USING pad()")
zero_arr = np.zeros((n, m), int)
# print(zero_arr)
bordered_2d = np.pad(zero_arr, pad_width=1, mode='constant', constant_values=1)
print(bordered_2d)

print("\n\nUSING NAIVE METHOD")
A = []
for i in range(n):
    for j in range(m):
        if (i == 0) or (i == n-1) or (j == 0) or ( j == m-1):
            A.append(1)
        else:
            A.append(0)
print(A)
print(np.array(A).reshape(n, m))

USING pad()
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


USING NAIVE METHOD
[1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
# 16th - Ghosts
np_array = [[1, 2],[3, 4]] 
bordered = np.pad(np_array, pad_width=1, mode='constant', constant_values=0)
print(bordered)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [66]:
print("The algorithm first checks if one of the operands is NaN before checking their types and if so it will return false")
print("0 * np.nan : ",0 * np.nan)
print("np.nan == np.nan : ",np.nan == np.nan) 
print("np.inf > np.nan : ",np.inf > np.nan)
print("np.nan - np.nan :", np.nan - np.nan)
print("np.nan in set([np.nan]) :", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1 :", 0.3 == 3 * 0.1) # [3*0.1=0.30000000000000004]

The algorithm first checks if one of the operands is NaN before checking their types and if so it will return false
0 * np.nan :  nan
np.nan == np.nan :  False
np.inf > np.nan :  False
np.nan - np.nan : nan
np.nan in set([np.nan]) : True
0.3 == 3 * 0.1 : False


#### 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)

In [2]:
import numpy as np
np.diag(np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0]])

In [109]:
# 18th - Ghosts
zeros_44 = np.zeros((4,4), dtype=int)
seq = np.arange(3)
# print(seq)
zeros_44[seq+1, seq] = np.arange(3) 
print(zeros_44)

[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]]


#### 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
---



In [113]:
# 19th - Ghosts
null_vector = np.zeros((10),dtype=int)
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


#### 22. Normalize a 5x5 random matrix (★☆☆) Say X is 5*5 numpy array  Normalize i.e X - mean(X) / Standard Deviation of X [link text](https://)

In [4]:
# 22nd - Ghosts
import numpy as np
a_55 = np.random.randint(1,50,(5,5))
a_55_norm = (a_55 - np.mean(a_55)) / np.std(a_55)
print(a_55)
print(a_55_norm)

[[15 10 43 22  6]
 [27 32 16 47 30]
 [ 3 20 21 40  4]
 [36 19 30  3 40]
 [19  6 18 16 34]]
[[-0.56388111 -0.9511621   1.6048924  -0.02168774 -1.26098689]
 [ 0.36559325  0.75287423 -0.48642492  1.91471719  0.59796184]
 [-1.49335548 -0.17660013 -0.09914393  1.37252381 -1.41589928]
 [ 1.06269902 -0.25405633  0.59796184 -1.49335548  1.37252381]
 [-0.25405633 -1.26098689 -0.33151252 -0.48642492  0.90778663]]


#### 23. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [5]:
# 23rd - Ghosts
array_1 = np.array([[1,2,3],[4,5,6]])
print(array_1[array_1<4])

[1 2 3]


#### 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
# 24th - Ghosts 
a_53 = np.random.randint(1,20,(5,3))
a_32 = np.random.randint(1,20,(3,2))
print(a_53)
print(a_32)
print(np.dot(a_53, a_32))

[[14 11  3]
 [18  5 12]
 [ 1 16 11]
 [18  6  5]
 [12  6 13]]
[[ 2  4]
 [ 7 19]
 [10  7]]
[[135 286]
 [191 251]
 [224 385]
 [128 221]
 [196 253]]


#### 25. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
# 25th - Ghosts 
A_R1 = np.random.randint(1,5,(3,3))
B_R1 = np.random.randint(1,5,(3,3))
print(A_R1)
print(B_R1)
print(np.array_equal(A_R1, B_R1)) # to check complete Array
print(A_R1 == B_R1) # to check every elements of Array
print(np.allclose(A_R1, B_R1))
A1 = [[1,2,3],[4,5],[6,7,8],[9]]
B1 = [[1,2,3],[4,5],[6,7,8],[10]]
print(np.array_equal(A1, B1))
print(A1 == B1)

[[2 3 3]
 [2 1 4]
 [2 3 4]]
[[3 3 4]
 [3 4 4]
 [2 3 2]]
False
[[False  True False]
 [False False  True]
 [ True  True False]]
False
False
False


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py:2440: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1, a2 = asarray(a1), asarray(a2)


#### 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [25]:
# 26th - Ghosts 
a_10 = np.random.randint(1,10,(10))
temp = a_10
print(a_10)
max_value = np.max(a_10)
print(max_value)

# using argmax
Z[Z.argmax()] = 0

# using condition
a_10[a_10 == max_value] = 0
print(a_10)
# using select function
a_10_new = np.select([a_10 == max_value], [0], temp)
print(a_10_new)

[6 7 1 1 4 9 1 7 5 8]
9
[6 7 1 1 4 0 1 7 5 8]
[6 7 1 1 4 0 1 7 5 8]


#### 27. Subtract the mean of each row of a matrix (★★☆):

In [38]:
# 27th - Ghosts 
A_R1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A_R1)
mean = np.mean(A_R1, axis=1)
print(mean)
print(A_R1 - mean)
print(A_R1 - mean.reshape(3,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 5. 8.]
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
